### ISSUE TITLE
Not all files are removed when uninstalling

### ISSUE THREAD

**Issue by Scorpi** [1111mp/nvm-desktop#34]
Hi!

I tried to uninstall nvm-desktop, and it seems not all files were removed.

These files were still present after uninstall:
```
C:\Users\User\AppData\Roaming\NVM-Desktop
C:\Users\User\AppData\Local\Programs\nvm-desktop
C:\Users\User\.nvmd
```

Also, it seems that `C:\Users\User\.nvmd` wasn't automatically removed from `PATH` variable, so nvmd still handles commands even after uninstall.
```
> node --version
nvm-desktop: command not found: node
```

**UPDATE:**
After I tried to remove these folders manually, I found out that nvm-desktop was still actually running in background.
Maybe that's why these files were not removed. Probably we need to kill active processes in uninstall process.
Also it seems that it allows to run multiple instances at once, and they all hide in system tray, that was one of the reasons why I didn't notice it at first time.

**Comment by 1111mp** [comment]
Please check this document to uninstall nvm-desktop completely: [uninstall](https://github.com/1111mp/nvm-desktop#uninstall)

Currently you have to manually delete `%HOMEPATH%\.nvmd\bin` from the environment variables and also manually delete the entire `%HOMEPATH%\.nvmd` file.

> After I tried to remove these folders manually, I found out that nvm-desktop was still actually running in background.
Maybe that's why these files were not removed. Probably we need to kill active processes in uninstall process.
Also it seems that it allows to run multiple instances at once, and they all hide in system tray, that was one of the reasons why I didn't notice it at first time.
​
`nvm-desktop` will not run multiple instances, and the code is completely open source, so you can rest assured. The closed window is minimized to the system tray by default, so perhaps you should choose to exit the application directly.
