### ISSUE TITLE
MacOS M1 is says app files is corrupted.

### ISSUE THREAD

**Issue by acroyear** [1111mp/nvm-desktop#67]
https://github.com/1111mp/nvm-desktop/releases/download/v3.2.0/nvm-desktop_Setup_mac_arm64_3.2.0.dmg

this file refused to run after following basic installation instructions

**Comment by acroyear** [comment]
says "is damaged. you should eject the disk image."

**Comment by acroyear** [comment]
the file within the .zip also says 'is damaged'

**Comment by 1111mp** [comment]
Yes, because `nvm-desktop` is not packaged with a certificate signature (this requires an `Apple` developer account). This is the default security policy of macOS systems for applications without certificate signatures. The solution is to manually set it up to allow it to run on your device. You can find more detailed instructions and solutions here: ["File/App is damaged and cannot be opened. You should move it to Trash."](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#macos-issues)

If you later want to remove `nvm-desktop` from your device, you can also view the documentation here to uninstall it completely: [nvm-desktop uninstall](https://github.com/1111mp/nvm-desktop?tab=readme-ov-file#uninstall)
