### ISSUE TITLE
zsh: bad CPU type in executable: nvmd

### ISSUE THREAD

**Issue by hardingCheng** [1111mp/nvm-desktop#8]
这在intel芯片会出现这个问题

**Comment by 1111mp** [comment]
On Macos or Windows?

**Comment by hardingCheng** [comment]
Macos  的  是intel版本的 



| |
徐文成
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 09/28/2023 17:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [1111mp/nvm-desktop] zsh: bad CPU type in executable: nvmd (Issue #8) |

On Macos or Windows?

**Comment by hardingCheng** [comment]
Mac  intel

| |
徐文成
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 09/28/2023 17:31 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
Your ***@***.***> |
| Subject | Re: [1111mp/nvm-desktop] zsh: bad CPU type in executable: nvmd (Issue #8) |

Macos 的 是intel版本的



| |
徐文成
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 09/28/2023 17:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [1111mp/nvm-desktop] zsh: bad CPU type in executable: nvmd (Issue #8) |

On Macos or Windows?

**Comment by 1111mp** [comment]
I should build the executable separately for x64 architecture Macos. Sorry I overlooked the compatibility issues of different architectures.
I will compile an executable for x64 Macos later. Since I don't currently have a device to test with, I can't confirm if the issue is actually resolved. I will provide the download address. If you have time, can you help test it?
（It only requires a very simple operation, just replace the `$PATH/.nvmd/bin/nvmd` file.）
Thank you.

**Comment by 1111mp** [comment]
https://github.com/1111mp/nvmd-command/releases/download/v2.2.0/Macos-x64.zip
This is the executable built for `x64 Macos`, you can download it and decompress it locally and then replace `$HOME/.nvmd/bin/nvmd` with the newly downloaded file. Then test if it works properly.

**Comment by 1111mp** [comment]
If the problem persists, please tell me what command you are executing to get the error. Thank you.

**Comment by 1111mp** [comment]
It has been resolved in [Releases v2.2.0](https://github.com/1111mp/nvm-desktop/releases/tag/v2.2.0). Please download the latest installation package.
